[tool.pyprojectx.jupyter]
requirements = [
    "IPython ~=8.8",
    "ipykernel ~=6.20",
    "ipywidgets ~=8.0",
    "jupyter_client ~=7.4",
    "jupyter_core ~=5.1",
    "nbclient ~=0.7",
    "nbconvert ~=7.2",
    "nbformat ~=5.7",
    "notebook ~=6.5",
    "qtconsole ~=5.4",
    "traitlets ~=5.8",
    "RISE ~=5.7",
    "jupyter_contrib_nbextensions ~=0.7",
]
post-install = """
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable autoscroll/main --sys-prefix
jupyter nbextension enable scroll_down/main --sys-prefix"""

[tool.pyprojectx.jupyter-latest]
requirements = [
    "jupyter",
    "RISE",
    "jupyter_contrib_nbextensions",
]
post-install = """
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable autoscroll/main --sys-prefix
jupyter nbextension enable scroll_down/main --sys-prefix"""

[tool.pyprojectx.aliases]
start = "jupyter notebook slides.ipynb -y" # -y will auto answer yes when stopping the server with ctrl+c
generate-slides = "jupyter nbconvert --to slides *.ipynb && python -m process_html"
clean = "rm -r .ipynb_checkpoints *.slides.html"

latest-start = "@jupyter-latest: jupyter notebook slides.ipynb -y" # -y will auto answer yes when stopping the server with ctrl+c

[tool.pyprojectx.os.win.aliases]
clean = "rmdir /s/q .ipynb_checkpoints *.slides.html"
