[tool.pyprojectx.jupyter]
requirements = [
    "IPython ~=8.0",
    "ipykernel ~=6.9",
    "ipywidgets ~=7.6",
    "jupyter_client ~=7.1",
    "jupyter_core ~=4.9",
    "nbclient ~=0.5",
    "nbconvert ~=6.4",
    "nbformat ~=5.1",
    "notebook ~=6.4",
    "qtconsole ~=5.2",
    "traitlets ~=5.1",
    "RISE ~=5.7",
    "jupyter_contrib_nbextensions ~=0.5",
]
post-install="""
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable autoscroll/main --sys-prefix
jupyter nbextension enable scroll_down/main --sys-prefix"""

[tool.pyprojectx.aliases]
download-java-kernel = "python -m unzip_url https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip ijava"
install-java-kernel = "@jupyter:python ijava/install.py --sys-prefix"
start = "pw@download-java-kernel && pw@install-java-kernel && pw@jupyter notebook slides.ipynb -y" # -y will auto answer yes when stopping the server with ctrl+c
generate-slides = "jupyter nbconvert --to slides *.ipynb && python -m process_html"
clean = "rm -r .ipynb_checkpoints *.slides.html ijava"

[tool.pyprojectx.os.win.aliases]
clean = "rmdir /s/q .ipynb_checkpoints *.slides.html ijava"
