[tool.pyprojectx]
jupyter = """\
IPython ~= 8.0
ipykernel ~= 6.9
ipywidgets ~= 7.6
jupyter_client ~= 7.1
jupyter_core ~= 4.9
nbclient ~= 0.5
nbconvert ~= 6.4
nbformat ~= 5.1
notebook ~= 6.4
qtconsole ~= 5.2
traitlets ~= 5.1
RISE ~= 5.7
jupyter_contrib_nbextensions ~=0.5

sos ~= 0.22
sos-notebook ~= 0.23
"""

[tool.pyprojectx.aliases]
npm-install = "npm i"
install-sos-kernel = "@jupyter:python -m sos_notebook.install --sys-prefix"
install-tslab-kernels = "@jupyter:python node_modules/tslab/python/install.py --sys-prefix --tslab node_modules/.bin/tslab"
start = "pw@npm i && pw@install-sos-kernel && pw@install-tslab-kernels && pw@jupyter notebook slides.ipynb -y" # -y will auto answer yes when stopping the server with ctrl+c
generate-slides = "jupyter nbconvert --to slides *.ipynb && python -m process_html"
clean = "rm -r .venv .pytest_cache dist ijava *.slides.html"

[tool.pyprojectx.os.win.aliases]
clean = "rmdir /s/q .venv .pytest_cache dist ijava"
